### ISSUE TITLE
not a bug, but where did the discord go

### ISSUE THREAD

**Issue by Divlocket** [JackTYM/AIOMacro#8]
where is the discord

**Comment by GamerCoder215** [comment]
@XHellMaster said that it was flagged by Discord because the mod is illegal

**Comment by JackTYM** [comment]
the mod isn't illegal, but it was terminated by Discord for distrubuting cheats, as well as my main account. A new discord server will be created soon

**Comment by JackTYM** [comment]
discord is back! discord.gg/EmCSfgSSaM
